[[게시글-API]]
== 게시글 API

[[게시글-작성]]
=== `POST` 게시글 작성

operation::post-controller-test/create-post[snippets='http-request,curl-request,request-headers,request-fields,http-response']

[[게시글-상세-조회]]
=== `GET` 게시글 상세 조회

operation::post-controller-test/find-post[snippets='http-request,curl-request,path-parameters,http-response,response-fields']

[[사진-투표-현황-조회]]
=== `GET` 사진 투표 현황 조회

operation::post-controller-test/find-vote-status[snippets='http-request,curl-request,request-headers,path-parameters,http-response,response-fields']


[[내가-작성한-게시글-조회]]
=== `GET` 내가 작성한 게시글 조회

operation::post-controller-test/find-my-post[snippets='http-request,curl-request,query-parameters,request-headers,http-response,response-fields']

[[내가-참여한-게시글-조회]]
=== `GET` 내가 참여한 게시글 조회

operation::post-controller-test/find-voted-post[snippets='http-request,curl-request,query-parameters,request-headers,http-response,response-fields']

[[게시글-삭제]]
=== 게시글 삭제 (미구현)

operation::post-controller-test/delete-post[snippets='http-request,curl-request,path-parameters,request-headers,http-response']
