[[게시글-API]]
== 게시글 API

[[게시글-작성]]
=== `POST` 게시글 작성

operation::post-controller-test/create-post[snippets='http-request,curl-request,request-headers,request-fields,http-response']

[[게시글-상세-조회]]
=== `GET` 게시글 상세 조회

operation::post-controller-test/find-post[snippets='http-request,curl-request,path-parameters,http-response,response-fields']

[[개사굴-공유-url-조회]]
=== `GET` 게시글 공유 url 조회

operation::post-controller-test/find-post_share-url[snippets='http-request,curl-request,path-parameters,http-response,response-fields']

[[유저가-작성한-게시글-조회]]
=== `GET` 유저가 작성한 게시글 조회

operation::post-controller-test/find-my-post[snippets='http-request,curl-request,query-parameters,request-headers,http-response,response-fields']

[[유저가-참여한-게시글-조회]]
=== `GET` 유저가 참여한 게시글 조회

operation::post-controller-test/find-voted-post[snippets='http-request,curl-request,query-parameters,request-headers,http-response,response-fields']

[[게시글-투표-수정]]
=== `POST` 게시글 노출 변경

operation::post-controller-test/toggle-status-post[snippets='http-request,curl-request,path-parameters,request-headers,http-response']

[[게시글-투표-수정]]
=== `POST` 게시글 투표 수정 (미구현)

operation::post-controller-test/update-post[snippets='http-request,curl-request,path-parameters,request-headers,http-response']

[[게시글-투표-마감]]
=== `POST` 게시글 투표 마감

operation::post-controller-test/close-post[snippets='http-request,curl-request,path-parameters,request-headers,http-response']

[[게시글-삭제]]
=== `DELETE` 게시글 삭제

operation::post-controller-test/delete-post[snippets='http-request,curl-request,path-parameters,request-headers,http-response']
