name: cd dev

on:
  pull_request:
    branches: [ "develop", "main" ]
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
  
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
  
      - name: Build with Gradle
        run: ./gradlew clean build
        
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          working-directory: ./
          name: photopic-dev-jar
          path: ./**/*.jar        
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: photopic-dev-jar

      - name: Build and deploy
        run: |
          echo "$SSH_PEM_KEY" >> $HOME/key.pem
          chmod 400 $HOME/key.pem
          ssh -i $HOME/key.pem ${SSH_USER}@${SSH_URL}
          sudo fuser -k -n tcp 3000 || true
          sudo nohup java -jar ./build/libs/*SNAPSHOT.jar &
        env:
          SSH_USER: ${{ secrets.AWS_EC2_USER }}
          SSH_URL: ${{secrets.AWS_EC2_URL_DEV}}
          SSH_PEM_KEY: ${{ secrets.AWS_EC2_KEY }}
        
