name: cd dev

on:
  pull_request:
    branches: [ "develop", "main" ]
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
  
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
  
      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: build/libs
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: Package

      - name: Display downloaded file
        run: ls -R

      - name: Build and deploy
        run: |
          echo "${{ secrets.AWS_EC2_KEY }}" | tr -d '\r' > $HOME/key.pem
          chmod 400 $HOME/key.pem
          scp -i $HOME/key.pem ./photopic*.jar ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_URL_DEV }}:~
          ssh -i $HOME/key.pem ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_URL_DEV }} "sudo fuser -k -n tcp 3000 || true && nohup java -jar photopic*.jar &"
        
