name: ci

on:
  pull_request:
    branches: [ 'develop' , 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.SUBMODULE_TOKEN }}
        submodules: true
      
    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Cache Gradle
      id: cache-gradle
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Copy application.yml
      run: cp ./server-config/*.yml ./src/main/resources/
      
    - name: Test with Gradle
      run: ./gradlew test
    
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v5
      if: always()
      with:
        report_paths: "**/build/test-results/test/TEST-*.xml"
